# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ed3342a5c0a4078b56270d15e73c6ae55525c283f9d99e9d37f01bc5b38d7a4f297a873c4f701494f925844472828bea881c07e90537f35f66fbf660d7e10e

test:
  secret_key_base: 7f1dcc48efddbb94de894b854f0d07db103af2b62f7d52e16d7567364d2bee60290d68651dc0396f351d37c1ada3e89bf39b4e27b04bea4da11d9160f73963db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
